"""
Django settings for testMS project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType 
import cx_Oracle


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qr)wz#mu#_0t9-h_k+!%l1hj6#8#%i0%+1+t2!&$s26q1anw2^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['172.24.192.90','172.24.193.109',
'127.0.0.1','172.24.216.50', '172.24.122.140',
'172.24.193.96']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CP',
    'Homepage',
    'CS',
    'Report',
    'groupadmin_users',
    'Tableau',
    'django_celery_results',
    'django_celery_beat',
    'CC',
    'QATool'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'testMS/templates/Login'),
            os.path.join(BASE_DIR, 'testMS/templates/CP'),
            os.path.join(BASE_DIR, 'testMS/templates/Index'),
            os.path.join(BASE_DIR, 'testMS/templates/CS'),
            os.path.join(BASE_DIR, 'testMS/templates/Report'),
            os.path.join(BASE_DIR, 'testMS/templates/Tableau'),
            os.path.join(BASE_DIR, 'testMS/templates/CC'),
            os.path.join(BASE_DIR, 'testMS/templates/QATool'),
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/login',
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/VNpost',
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/index',
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/feedback',
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/Reports',
            # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/templates/Tableau'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testMS.wsgi.application'

# SESSION_ENGINE = "django.contrib.sessions.backends.file"
# SESSION_FILE_PATH = "/OPS_MIS/Py Thông/testMS/tmp/django_cache"

SESSION_SAVE_EVERY_REQUEST = True  


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'oracle': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'DBHDWVN-VIETTEL.PROD.ITC.HCNET.VN:1521/HDWVN.HOMECREDIT.VN',
        'USER': 'APP_REPORT_INT[AP_OPS]',
        'PASSWORD': 'Xcvert6uiopp',
        
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'sqllite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'vnvxdbtst01.hcnet.vn:1521/oratest.hcnet.vn',
        'USER': 'APP_OPS',
        'PASSWORD': 'app_ops1test',
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'CHARSET' : 'utf-8'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = False

DEFAULT_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static_resources')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "testMS/static/login/"),
    # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/static/login/',
    os.path.join(BASE_DIR, "testMS/static/index/"),
    # '/hungnn/GitLab/OPS_MIS/Py Thông/testMS/testMS/static/index/',
    # os.path.join(BASE_DIR, 'static/index/'),
    # os.path.join(BASE_DIR, 'testMS/static/')
]


# AUTHENTICATION_BACKENDS = [
#     # 'django_auth_ldap.backend.LDAPBackend',
#     #'django.contrib.auth.backends.ModelBackend',
# ]

BROKER_URL = 'amqp://localhost'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_RESULT_BACKEND = 'django-db'
#CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'


CACHES = {
    'default': {
    'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    'LOCATION': 'cache',
    'TIMEOUT': None,
    }
}

